### ISSUE TITLE
Keith's content to-do list

### ISSUE THREAD

**Issue by keith-kurak** [keith-kurak/expo-router-london-2024-lessons#1]
Code template / general:
- [ ] Naming issues/discrepancies that are vestiges of the last workshop: 
  - [ ] departments -> exhibits
  - [ ]  sign in -> login
- [ ] Remove the local storage fallback code
- [ ] Some files that aren't needed
- [ ] responsive tab styling could be better
- [ ] safe area stuff doesn't work on iOS; probably will not use Nativewind for that because it's experimental

Module 01:
- [ ] Exercise 2 nested route behavior bugs (possible workaround for some: just remove the department link):
  - [ ] some of the routes are getting put into query params when going back from a department from the Home tab
  - [ ] `lazy=false` initial route issue (affects Module 03, with no known workaround for headless tabs)
  - [ ] back/forward browser button behavior is broken (https://github.com/expo/expo/issues/31747)

Module 03:
- [ ] Figure out if you can figure out the bonus (it'd be really engaging if someone has a lot of router experience)
